{
 "title": "Consul Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "service",
    "query": "label_values(consul_catalog_service_node_healthy, service_name)"
   },
   {
    "name": "node",
    "query": "label_values(consul_catalog_service_node_healthy{service_name=~\"$service\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "Monitoring status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "consul_exporter up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"consul_exporter\"}"
    }
   ]
  },
  {
   "title": "consul up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_up" }
   ]
  },
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "repeat": "service",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (consul_catalog_service_node_healthy{service_name=\"$service\", node=~\"$node\"})",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "consul_health_service_status{service_name=\"$service\", node=~\"$node\", status!=\"passing\"} > 0",
     "legendFormat": "{{node}} {{status}}"
    }
   ]
  }
 ]
}