{
 "title": "Consul Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "consuls up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"consul-servers\"})"
    }
   ]
  },
  {
   "title": "autopilot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(consul_autopilot_healthy)" }
   ]
  },
  {
   "title": "candidate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_raft_state_candidate)"
    }
   ]
  },
  {
   "title": "raft: GC pausing over prev minute",
   "type": "graph",
   "description": "see [doc](https://www.consul.io/docs/agent/telemetry.html#leadership-changes)",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(consul_runtime_total_gc_pause_ns[1m])/1000000"
    }
   ]
  },
  {
   "title": "raft: time for leader to contact followers - 99th%",
   "type": "graph",
   "description": "see [doc](https://www.consul.io/docs/agent/telemetry.html#leadership-changes)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "raft: replication heartbeat - 99th%",
   "type": "graph",
   "description": "see [doc](https://www.consul.io/docs/agent/telemetry.html#leadership-changes)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_replication_heartbeat{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "raft: transaction rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(consul_raft_apply[1m])" }
   ]
  },
  {
   "title": "raft: transaction commit time - 99th%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_commitTime{quantile=\"0.99\"}"
    }
   ]
  }
 ]
}