{
 "title": "Nomad Clients",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "allocations running",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocations_running)"
    }
   ]
  },
  {
   "title": "cpu allocation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocated_cpu) /\n                     (sum without(job, node_id) (nomad_client_allocated_cpu)\n                     +sum without(job, node_id) (nomad_client_unallocated_cpu))"
    }
   ]
  },
  {
   "title": "allocations blocked",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocations_blocked)"
    }
   ]
  },
  {
   "title": "disk allocation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocated_disk) /\n                     (sum without(job, node_id) (nomad_client_allocated_disk)\n                     +sum without(job, node_id) (nomad_client_unallocated_disk))"
    }
   ]
  },
  {
   "title": "allocations migrating",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocations_migrating)"
    }
   ]
  },
  {
   "title": "memory allocation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocated_memory) /\n                     (sum without(job, node_id) (nomad_client_allocated_memory)\n                     +sum without(job, node_id) (nomad_client_unallocated_memory))"
    }
   ]
  },
  {
   "title": "allocations pending",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocations_pending)"
    }
   ]
  },
  {
   "title": "allocations terminal",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, node_id) (nomad_client_allocations_terminal)"
    }
   ]
  }
 ]
}