{
 "title": "Nomad Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "jobs running",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_running)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  },
  {
   "title": "jobs queued",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_queued)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  },
  {
   "title": "jobs complete",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_complete)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  },
  {
   "title": "jobs failed",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_failed)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  },
  {
   "title": "jobs starting",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_starting)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  },
  {
   "title": "jobs lost",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(task_group,exported_job) (nomad_nomad_job_summary_lost)",
     "legendFormat": "{{task_group}}.{{exported_job}}"
    }
   ]
  }
 ]
}