{
 "title": "Vault on Consul - Merged",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "10s,30s,1m,5m,15m" },
   { "name": "quantile", "query": "0.5,0.9,0.99" },
   {
    "name": "route_query",
    "query": "{__name__=~\"vault_route.+_count\"}"
   }
  ]
 },
 "panels": [
  { "title": "Node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device!~\"^(md[0-9]+$|dm-)\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Negative=transmit, Positive=receive",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$interval])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes\n         - node_memory_MemFree_bytes\n         - node_memory_Buffers_bytes\n         - node_memory_Cached_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes\n                    + node_memory_Cached_bytes",
     "legendFormat": "Buffers+Cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request $interval Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_core_handle_request_count[$interval])"
    }
   ]
  },
  {
   "title": "Barrier $interval rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_barrier_get_count[$interval])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(vault_barrier_put_count[$interval])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(vault_barrier_list_count[$interval])",
     "legendFormat": "LIST"
    },
    {
     "expr": "rate(vault_barrier_delete_count[$interval])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Consul Backend $interval Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_consul_get_count[$interval])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(vault_consul_put_count[$interval])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(vault_consul_list_count[$interval])",
     "legendFormat": "LIST"
    },
    {
     "expr": "rate(vault_consul_delete_count[$interval])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Tokens $interval Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vault_token_createAccessor_count[$interval])",
     "legendFormat": "createAccessor"
    },
    {
     "expr": "rate(vault_token_create_count[$interval])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(vault_token_lookup_count[$interval])",
     "legendFormat": "lookup"
    },
    {
     "expr": "rate(vault_token_revoke_count[$interval])",
     "legendFormat": "revoke"
    },
    {
     "expr": "rate(vault_token_revoke_tree_count[$interval])",
     "legendFormat": "revoke_tree"
    },
    {
     "expr": "rate(vault_token_store_count[$interval])",
     "legendFormat": "store"
    }
   ]
  },
  { "title": "Request Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Handle Request Time - $quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "repeat": "quantile",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_login_request{quantile=~\"$quantile\"}",
     "legendFormat": "login_request"
    },
    {
     "expr": "vault_core_handle_request{quantile=~\"$quantile\"}",
     "legendFormat": "request"
    },
    {
     "expr": "vault_core_check_token{quantile=~\"$quantile\"}",
     "legendFormat": "check_token"
    },
    {
     "expr": "vault_core_fetch_acl_and_token{quantile=~\"$quantile\"}",
     "legendFormat": "fetch_acl_and_token"
    }
   ]
  },
  { "title": "Backend Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Barrier Time - $quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "repeat": "quantile",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_get{quantile=~\"$quantile\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "vault_barrier_put{quantile=~\"$quantile\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "vault_barrier_list{quantile=~\"$quantile\"}",
     "legendFormat": "LIST"
    },
    {
     "expr": "vault_barrier_delete{quantile=~\"$quantile\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Consul Backend Time - $quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "repeat": "quantile",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_consul_get{quantile=~\"$quantile\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "vault_consul_put{quantile=~\"$quantile\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "vault_consul_list{quantile=~\"$quantile\"}",
     "legendFormat": "LIST"
    },
    {
     "expr": "vault_consul_delete{quantile=~\"$quantile\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "Token Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Tokens - $quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "repeat": "quantile",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_token_createAccessor{quantile=~\"$quantile\"}",
     "legendFormat": "createAccessor"
    },
    {
     "expr": "vault_token_create{quantile=~\"$quantile\"}",
     "legendFormat": "create"
    },
    {
     "expr": "vault_token_revoke{quantile=~\"$quantile\"}",
     "legendFormat": "revoke"
    },
    {
     "expr": "vault_token_revoke_tree{quantile=~\"$quantile\"}",
     "legendFormat": "revoke_tree"
    },
    {
     "expr": "vault_token_store{quantile=~\"$quantile\"}",
     "legendFormat": "store"
    },
    {
     "expr": "vault_token_lookup{quantile=~\"$quantile\"}",
     "legendFormat": "lookup"
    }
   ]
  },
  { "title": "Route Timings And Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$route_query - $quantile - $interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "repeat": "route_query",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(${route_query}_count[$interval])",
     "legendFormat": "rate"
    },
    {
     "expr": "$route_query{quantile=~\"$quantile\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}